# Generated by Django 3.1.2 on 2020-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Модель')),
                ('image', models.TextField(verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('release_date', models.DateField(verbose_name='Дта релиза')),
                ('lte_exists', models.BooleanField(verbose_name='ЛТЕ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
